### ISSUE TITLE
Can't move the guideline

### ISSUE THREAD

**Issue by nmassi** [Mark2Mark/Show-Stems#1]
Hi, I can't move the guideline, seeing at the console I got this >

5/27/16 1:00:29.548 PM Glyphs[14798]: Traceback (most recent call last):
  File "/Users/nico/Library/Application Support/Glyphs/Plugins/ShowStems.glyphsReporter/Contents/Resources/plugin.py", line 112, in verticalStems
    savedMeasurements = thisFont.userData["GSDimensionPlugin.Dimensions"][thisMasterID]
TypeError: 'NoneType' object has no attribute '**getitem**'

**Comment by Mark2Mark** [comment]
Can you move the Glyphsapp built-in measurement line when in text mode? Use ctrl+opt+cmd to move it. The Show-Stems-Line is attached to its position.

If this is still an issue, please let me know.

**Comment by nmassi** [comment]
Thanks Mark. I wasn't in text mode :)
